
export enum CardReducerEnum {
    SET_CARDS='SET_CARDS',
    SET_FILTERED_CARDS='SET_FILTERED_CARDS',
    SET_FAVORITE_CARDS='SET_FAVORITE_CARDS',
    SET_SELECTED_CARD='SET_SELECTED_CARD',
SET_SEARCH_KEYWORD='SET_SEARCH_KEYWORD'
}